logging:
  level:
    hello:
      springmvc: debug
    root: info

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  mysql:

  jpa:
    database:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    web-application-type: none

jwt:
  secret: fjewiofjewif3f32if32i3i33@@!!!313212!!212!!@2222fgr3g12fewfewf3223r23@333232!!