logging:
  level:
    hello:
      springmvc: debug
    root: info

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  mysql:

  jpa:
    database:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
